name: Build rctop

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release;cp target/release/rctop .
    - name: Run tests
      run: cargo test --verbose --release
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Build artifact
        path: rctop
